#!/usr/bin/env python

from __future__ import division
from geode import *
from geode.value import parser

props = PropManager()
input = props.add('input','').set_required(1)
output = props.add('output','').set_abbrev('o').set_required(1)
extra = props.add('extra',100).set_abbrev('e').set_required(1)
parser.parse(props,'Stitch several overlapping image tiles together',positional=[input])

# Read input
small = Image.read(input())

# Extend
shape = small.shape
large = zeros((shape[0],shape[1]+extra(),3))
large[:,:shape[1]] = small
large[:,shape[1]:] = small[:,-1].reshape(-1,1,3)

# Write output
Image.write(output(),large)
